---

kind: pipeline
name: backend

steps:
  - name: run Python tests
    image: python:3.12
    commands:
      - pip install poetry
      - cd backend
      - poetry install
      - poetry run pytest

  - name: check Python format
    image: python:3.12
    commands:
      - pip install poetry
      - cd backend
      - poetry install
      - poetry run black --check garden_water
      - poetry run isort --check garden_water

---

kind: pipeline
name: frontend

steps:
  - name: build frontend
    image: node:20-alpine
    commands:
      - cd frontend
      - yarn build
